services:
  gateway:
    build:
      context: .
      dockerfile: apps/gateway/Dockerfile
    container_name: gateway
    ports:
      - '3000:3000'
    env_file:
      - ./apps/gateway/.env.dev

  auth:
    build:
      context: .
      dockerfile: apps/auth/Dockerfile
    container_name: auth
    ports:
      - '3001:3001'
    env_file:
      - ./apps/auth/.env.dev

  event:
    build:
      context: .
      dockerfile: apps/event/Dockerfile
    container_name: event
    ports:
      - '3002:3002'
    env_file:
      - ./apps/event/.env.dev
